package com.project.donate.bootstrap;


import com.project.donate.enums.Role;
import com.project.donate.model.*;
import com.project.donate.repository.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.log4j.Log4j2;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Component
@Profile("bootstrap")
@Transactional
@Log4j2
@RequiredArgsConstructor
public class Bootstrap implements CommandLineRunner {


    private final CityRepository cityRepository;
    private final RegionRepository regionRepository;
    private final UserRepository userRepository;
    private final CategoryRepository categoryRepository;
    private final AddressRepository addressRepository;
    private final PasswordEncoder passwordEncoder;


    @Override
    public void run(String... args) throws Exception {


        if (cityRepository.count() < 1) {

            List<Category> categories = List.of(
                    // Fruits & Vegetables
                    Category.builder().name("Fresh Fruits").build(),
                    Category.builder().name("Fresh Vegetables").build(),
                    Category.builder().name("Organic Produce").build(),
                    Category.builder().name("Cut & Ready Produce").build(),
                    Category.builder().name("Dried Fruits & Vegetables").build(),

                    // Meat, Chicken & Fish
                    Category.builder().name("Red Meat").build(),
                    Category.builder().name("Chicken Products").build(),
                    Category.builder().name("Fish & Seafood").build(),
                    Category.builder().name("Offal").build(),
                    Category.builder().name("Marinated Meats").build(),
                    Category.builder().name("Delicatessen (Sausage, Salami, etc.)").build(),

                    // Dairy & Breakfast
                    Category.builder().name("Milk").build(),
                    Category.builder().name("Cheese").build(),
                    Category.builder().name("Yogurt & Ayran").build(),
                    Category.builder().name("Butter & Margarine").build(),
                    Category.builder().name("Olives & Jams").build(),
                    Category.builder().name("Honey & Molasses").build(),
                    Category.builder().name("Eggs").build(),

                    // Bakery
                    Category.builder().name("Breads").build(),
                    Category.builder().name("Pastries & Savory Bakes").build(),
                    Category.builder().name("Cakes & Cookies").build(),
                    Category.builder().name("Frozen Bakery Products").build(),
                    Category.builder().name("Flour & Baking Ingredients").build(),

                    // Pantry / Dry Foods
                    Category.builder().name("Rice & Bulgur").build(),
                    Category.builder().name("Pasta & Noodles").build(),
                    Category.builder().name("Legumes (Lentils, Beans, etc.)").build(),
                    Category.builder().name("Flour, Sugar & Salt").build(),
                    Category.builder().name("Canned Foods").build(),
                    Category.builder().name("Tomato Paste & Sauces").build(),
                    Category.builder().name("Cooking Oils").build(),

                    // Beverages
                    Category.builder().name("Water & Mineral Water").build(),
                    Category.builder().name("Fruit Juices").build(),
                    Category.builder().name("Sodas & Soft Drinks").build(),
                    Category.builder().name("Energy Drinks").build(),
                    Category.builder().name("Tea & Herbal Teas").build(),
                    Category.builder().name("Coffee").build(),

                    // Snacks & Sweets
                    Category.builder().name("Chocolate & Wafer").build(),
                    Category.builder().name("Chips & Crackers").build(),
                    Category.builder().name("Nuts & Seeds").build(),
                    Category.builder().name("Ice Cream").build(),
                    Category.builder().name("Biscuits & Cakes").build(),

                    // Cleaning Supplies
                    Category.builder().name("Dishwashing Products").build(),
                    Category.builder().name("Laundry Products").build(),
                    Category.builder().name("General Cleaning Supplies").build(),
                    Category.builder().name("Paper Products").build(),
                    Category.builder().name("Personal Hygiene Products").build(),

                    // Personal Care
                    Category.builder().name("Hair Care").build(),
                    Category.builder().name("Skin Care").build(),
                    Category.builder().name("Oral Care").build(),
                    Category.builder().name("Deodorant & Perfume").build(),
                    Category.builder().name("Baby Care").build(),

                    // Baby Products
                    Category.builder().name("Diapers").build(),
                    Category.builder().name("Baby Food & Formula").build(),
                    Category.builder().name("Wet Wipes").build(),
                    Category.builder().name("Pacifiers & Bottles").build(),

                    // Pet Supplies
                    Category.builder().name("Cat & Dog Food").build(),
                    Category.builder().name("Litter & Accessories").build(),
                    Category.builder().name("Pet Vitamins & Treats").build(),

                    // Home & Lifestyle
                    Category.builder().name("Kitchenware").build(),
                    Category.builder().name("Small Home Appliances").build(),
                    Category.builder().name("Home Decoration").build(),
                    Category.builder().name("Garden & Outdoor").build(),
                    Category.builder().name("Stationery & Toys").build()
            );

            categoryRepository.saveAll(categories);

            log.info("Categories created by Bootstrap");
        }


        if (cityRepository.count() < 1) {

            List<City> cities = List.of(
                    new City("ADANA"),
                    new City("ADIYAMAN"),
                    new City("AFYONKARAHİSAR"),
                    new City("AĞRI"),
                    new City("AMASYA"),
                    new City("ANKARA"),
                    new City("ANTALYA"),
                    new City("ARTVİN"),
                    new City("AYDIN"),
                    new City("BALIKESİR"),
                    new City("BİLECİK"),
                    new City("BİNGÖL"),
                    new City("BİTLİS"),
                    new City("BOLU"),
                    new City("BURDUR"),
                    new City("BURSA"),
                    new City("ÇANAKKALE"),
                    new City("ÇANKIRI"),
                    new City("ÇORUM"),
                    new City("DENİZLİ"),
                    new City("DİYARBAKIR"),
                    new City("EDİRNE"),
                    new City("ELAZIĞ"),
                    new City("ERZİNCAN"),
                    new City("ERZURUM"),
                    new City("ESKİŞEHİR"),
                    new City("GAZİANTEP"),
                    new City("GİRESUN"),
                    new City("GÜMÜŞHANE"),
                    new City("HAKKARİ"),
                    new City("HATAY"),
                    new City("ISPARTA"),
                    new City("MERSİN"),
                    new City("İSTANBUL"),
                    new City("İZMİR"),
                    new City("KARS"),
                    new City("KASTAMONU"),
                    new City("KAYSERİ"),
                    new City("KIRKLARELİ"),
                    new City("KIRŞEHİR"),
                    new City("KOCAELİ"),
                    new City("KONYA"),
                    new City("KÜTAHYA"),
                    new City("MALATYA"),
                    new City("MANİSA"),
                    new City("KAHRAMANMARAŞ"),
                    new City("MARDİN"),
                    new City("MUĞLA"),
                    new City("MUŞ"),
                    new City("NEVŞEHİR"),
                    new City("NİĞDE"),
                    new City("ORDU"),
                    new City("RİZE"),
                    new City("SAKARYA"),
                    new City("SAMSUN"),
                    new City("SİİRT"),
                    new City("SİNOP"),
                    new City("SİVAS"),
                    new City("TEKİRDAĞ"),
                    new City("TOKAT"),
                    new City("TRABZON"),
                    new City("TUNCELİ"),
                    new City("ŞANLIURFA"),
                    new City("UŞAK"),
                    new City("VAN"),
                    new City("YOZGAT"),
                    new City("ZONGULDAK"),
                    new City("AKSARAY"),
                    new City("BAYBURT"),
                    new City("KARAMAN"),
                    new City("KIRIKKALE"),
                    new City("BATMAN"),
                    new City("ŞIRNAK"),
                    new City("BARTIN"),
                    new City("ARDAHAN"),
                    new City("IĞDIR"),
                    new City("YALOVA"),
                    new City("KARABÜK"),
                    new City("KİLİS"),
                    new City("OSMANİYE"),
                    new City("DÜZCE")
            );

            cityRepository.saveAll(cities);

            log.info("Saved Cities by Bootstrap");

        }

        if (regionRepository.count() < 1) {

            List<Region> regions = List.of(new Region("ALADAĞ", City.builder().id(1L).build()),
                    new Region("CEYHAN", City.builder().id(1L).build()),
                    new Region("ÇUKUROVA", City.builder().id(1L).build()),
                    new Region("FEKE", City.builder().id(1L).build()),
                    new Region("İMAMOĞLU", City.builder().id(1L).build()),
                    new Region("KARAİSALI", City.builder().id(1L).build()),
                    new Region("KARATAŞ", City.builder().id(1L).build()),
                    new Region("KOZAN", City.builder().id(1L).build()),
                    new Region("POZANTI", City.builder().id(1L).build()),
                    new Region("SAİMBEYLİ", City.builder().id(1L).build()),
                    new Region("SARIÇAM", City.builder().id(1L).build()),
                    new Region("SEYHAN", City.builder().id(1L).build()),
                    new Region("TUFANBEYLİ", City.builder().id(1L).build()),
                    new Region("YUMURTALIK", City.builder().id(1L).build()),
                    new Region("YÜREĞİR", City.builder().id(1L).build()),
                    new Region("BESNİ", City.builder().id(2L).build()),
                    new Region("ÇELİKHAN", City.builder().id(2L).build()),
                    new Region("GERGER", City.builder().id(2L).build()),
                    new Region("GÖLBAŞI", City.builder().id(2L).build()),
                    new Region("KAHTA", City.builder().id(2L).build()),
                    new Region("MERKEZ", City.builder().id(2L).build()),
                    new Region("SAMSAT", City.builder().id(2L).build()),
                    new Region("SİNCİK", City.builder().id(2L).build()),
                    new Region("TUT", City.builder().id(2L).build()),
                    new Region("BAŞMAKÇI", City.builder().id(3L).build()),
                    new Region("BAYAT", City.builder().id(3L).build()),
                    new Region("BOLVADİN", City.builder().id(3L).build()),
                    new Region("ÇAY", City.builder().id(3L).build()),
                    new Region("ÇOBANLAR", City.builder().id(3L).build()),
                    new Region("DAZKIRI", City.builder().id(3L).build()),
                    new Region("DİNAR", City.builder().id(3L).build()),
                    new Region("EMİRDAĞ", City.builder().id(3L).build()),
                    new Region("EVCİLER", City.builder().id(3L).build()),
                    new Region("HOCALAR", City.builder().id(3L).build()),
                    new Region("İHSANİYE", City.builder().id(3L).build()),
                    new Region("İSCEHİSAR", City.builder().id(3L).build()),
                    new Region("KIZILÖREN", City.builder().id(3L).build()),
                    new Region("MERKEZ", City.builder().id(3L).build()),
                    new Region("SANDIKLI", City.builder().id(3L).build()),
                    new Region("SİNANPAŞA", City.builder().id(3L).build()),
                    new Region("SULTANDAĞI", City.builder().id(3L).build()),
                    new Region("ŞUHUT", City.builder().id(3L).build()),
                    new Region("DİYADİN", City.builder().id(4L).build()),
                    new Region("DOĞUBAYAZIT", City.builder().id(4L).build()),
                    new Region("ELEŞKİRT", City.builder().id(4L).build()),
                    new Region("HAMUR", City.builder().id(4L).build()),
                    new Region("MERKEZ", City.builder().id(4L).build()),
                    new Region("PATNOS", City.builder().id(4L).build()),
                    new Region("TAŞLIÇAY", City.builder().id(4L).build()),
                    new Region("TUTAK", City.builder().id(4L).build()),
                    new Region("GÖYNÜCEK", City.builder().id(5L).build()),
                    new Region("GÜMÜŞHACIKÖY", City.builder().id(5L).build()),
                    new Region("HAMAMÖZÜ", City.builder().id(5L).build()),
                    new Region("MERKEZ", City.builder().id(5L).build()),
                    new Region("MERZİFON", City.builder().id(5L).build()),
                    new Region("SULUOVA", City.builder().id(5L).build()),
                    new Region("TAŞOVA", City.builder().id(5L).build()),
                    new Region("AKYURT", City.builder().id(6L).build()),
                    new Region("ALTINDAĞ", City.builder().id(6L).build()),
                    new Region("AYAŞ", City.builder().id(6L).build()),
                    new Region("BALA", City.builder().id(6L).build()),
                    new Region("BEYPAZARI", City.builder().id(6L).build()),
                    new Region("ÇAMLIDERE", City.builder().id(6L).build()),
                    new Region("ÇANKAYA", City.builder().id(6L).build()),
                    new Region("ÇUBUK", City.builder().id(6L).build()),
                    new Region("ELMADAĞ", City.builder().id(6L).build()),
                    new Region("ETİMESGUT", City.builder().id(6L).build()),
                    new Region("EVREN", City.builder().id(6L).build()),
                    new Region("GÖLBAŞI", City.builder().id(6L).build()),
                    new Region("GÜDÜL", City.builder().id(6L).build()),
                    new Region("HAYMANA", City.builder().id(6L).build()),
                    new Region("KAHRAMANKAZAN", City.builder().id(6L).build()),
                    new Region("KALECİK", City.builder().id(6L).build()),
                    new Region("KEÇİÖREN", City.builder().id(6L).build()),
                    new Region("KIZILCAHAMAM", City.builder().id(6L).build()),
                    new Region("MAMAK", City.builder().id(6L).build()),
                    new Region("NALLIHAN", City.builder().id(6L).build()),
                    new Region("POLATLI", City.builder().id(6L).build()),
                    new Region("PURSAKLAR", City.builder().id(6L).build()),
                    new Region("SİNCAN", City.builder().id(6L).build()),
                    new Region("ŞEREFLİKOÇHİSAR", City.builder().id(6L).build()),
                    new Region("YENİMAHALLE", City.builder().id(6L).build()),
                    new Region("AKSEKİ", City.builder().id(7L).build()),
                    new Region("AKSU", City.builder().id(7L).build()),
                    new Region("ALANYA", City.builder().id(7L).build()),
                    new Region("DEMRE", City.builder().id(7L).build()),
                    new Region("DÖŞEMEALTI", City.builder().id(7L).build()),
                    new Region("ELMALI", City.builder().id(7L).build()),
                    new Region("FİNİKE", City.builder().id(7L).build()),
                    new Region("GAZİPAŞA", City.builder().id(7L).build()),
                    new Region("GÜNDOĞMUŞ", City.builder().id(7L).build()),
                    new Region("İBRADI", City.builder().id(7L).build()),
                    new Region("KAŞ", City.builder().id(7L).build()),
                    new Region("KEMER", City.builder().id(7L).build()),
                    new Region("KEPEZ", City.builder().id(7L).build()),
                    new Region("KONYAALTI", City.builder().id(7L).build()),
                    new Region("KORKUTELİ", City.builder().id(7L).build()),
                    new Region("KUMLUCA", City.builder().id(7L).build()),
                    new Region("MANAVGAT", City.builder().id(7L).build()),
                    new Region("MURATPAŞA", City.builder().id(7L).build()),
                    new Region("SERİK", City.builder().id(7L).build()),
                    new Region("ARDANUÇ", City.builder().id(8L).build()),
                    new Region("ARHAVİ", City.builder().id(8L).build()),
                    new Region("BORÇKA", City.builder().id(8L).build()),
                    new Region("HOPA", City.builder().id(8L).build()),
                    new Region("KEMALPAŞA", City.builder().id(8L).build()),
                    new Region("MERKEZ", City.builder().id(8L).build()),
                    new Region("MURGUL", City.builder().id(8L).build()),
                    new Region("ŞAVŞAT", City.builder().id(8L).build()),
                    new Region("YUSUFELİ", City.builder().id(8L).build()),
                    new Region("BOZDOĞAN", City.builder().id(9L).build()),
                    new Region("BUHARKENT", City.builder().id(9L).build()),
                    new Region("ÇİNE", City.builder().id(9L).build()),
                    new Region("DİDİM", City.builder().id(9L).build()),
                    new Region("EFELER", City.builder().id(9L).build()),
                    new Region("GERMENCİK", City.builder().id(9L).build()),
                    new Region("İNCİRLİOVA", City.builder().id(9L).build()),
                    new Region("KARACASU", City.builder().id(9L).build()),
                    new Region("KARPUZLU", City.builder().id(9L).build()),
                    new Region("KOÇARLI", City.builder().id(9L).build()),
                    new Region("KÖŞK", City.builder().id(9L).build()),
                    new Region("KUŞADASI", City.builder().id(9L).build()),
                    new Region("KUYUCAK", City.builder().id(9L).build()),
                    new Region("NAZİLLİ", City.builder().id(9L).build()),
                    new Region("SÖKE", City.builder().id(9L).build()),
                    new Region("SULTANHİSAR", City.builder().id(9L).build()),
                    new Region("YENİPAZAR", City.builder().id(9L).build()),
                    new Region("ALTIEYLÜL", City.builder().id(10L).build()),
                    new Region("AYVALIK", City.builder().id(10L).build()),
                    new Region("BALYA", City.builder().id(10L).build()),
                    new Region("BANDIRMA", City.builder().id(10L).build()),
                    new Region("BİGADİÇ", City.builder().id(10L).build()),
                    new Region("BURHANİYE", City.builder().id(10L).build()),
                    new Region("DURSUNBEY", City.builder().id(10L).build()),
                    new Region("EDREMİT", City.builder().id(10L).build()),
                    new Region("ERDEK", City.builder().id(10L).build()),
                    new Region("GÖMEÇ", City.builder().id(10L).build()),
                    new Region("GÖNEN", City.builder().id(10L).build()),
                    new Region("HAVRAN", City.builder().id(10L).build()),
                    new Region("İVRİNDİ", City.builder().id(10L).build()),
                    new Region("KARESİ", City.builder().id(10L).build()),
                    new Region("KEPSUT", City.builder().id(10L).build()),
                    new Region("MANYAS", City.builder().id(10L).build()),
                    new Region("MARMARA", City.builder().id(10L).build()),
                    new Region("SAVAŞTEPE", City.builder().id(10L).build()),
                    new Region("SINDIRGI", City.builder().id(10L).build()),
                    new Region("SUSURLUK", City.builder().id(10L).build()),
                    new Region("BOZÜYÜK", City.builder().id(11L).build()),
                    new Region("GÖLPAZARI", City.builder().id(11L).build()),
                    new Region("İNHİSAR", City.builder().id(11L).build()),
                    new Region("MERKEZ", City.builder().id(11L).build()),
                    new Region("OSMANELİ", City.builder().id(11L).build()),
                    new Region("PAZARYERİ", City.builder().id(11L).build()),
                    new Region("SÖĞÜT", City.builder().id(11L).build()),
                    new Region("YENİPAZAR", City.builder().id(11L).build()),
                    new Region("ADAKLI", City.builder().id(12L).build()),
                    new Region("GENÇ", City.builder().id(12L).build()),
                    new Region("KARLIOVA", City.builder().id(12L).build()),
                    new Region("KİĞI", City.builder().id(12L).build()),
                    new Region("MERKEZ", City.builder().id(12L).build()),
                    new Region("SOLHAN", City.builder().id(12L).build()),
                    new Region("YAYLADERE", City.builder().id(12L).build()),
                    new Region("YEDİSU", City.builder().id(12L).build()),
                    new Region("ADİLCEVAZ", City.builder().id(13L).build()),
                    new Region("AHLAT", City.builder().id(13L).build()),
                    new Region("GÜROYMAK", City.builder().id(13L).build()),
                    new Region("HİZAN", City.builder().id(13L).build()),
                    new Region("MERKEZ", City.builder().id(13L).build()),
                    new Region("MUTKİ", City.builder().id(13L).build()),
                    new Region("TATVAN", City.builder().id(13L).build()),
                    new Region("DÖRTDİVAN", City.builder().id(14L).build()),
                    new Region("GEREDE", City.builder().id(14L).build()),
                    new Region("GÖYNÜK", City.builder().id(14L).build()),
                    new Region("KIBRISCIK", City.builder().id(14L).build()),
                    new Region("MENGEN", City.builder().id(14L).build()),
                    new Region("MERKEZ", City.builder().id(14L).build()),
                    new Region("MUDURNU", City.builder().id(14L).build()),
                    new Region("SEBEN", City.builder().id(14L).build()),
                    new Region("YENİÇAĞA", City.builder().id(14L).build()),
                    new Region("AĞLASUN", City.builder().id(15L).build()),
                    new Region("ALTINYAYLA", City.builder().id(15L).build()),
                    new Region("BUCAK", City.builder().id(15L).build()),
                    new Region("ÇAVDIR", City.builder().id(15L).build()),
                    new Region("ÇELTİKÇİ", City.builder().id(15L).build()),
                    new Region("GÖLHİSAR", City.builder().id(15L).build()),
                    new Region("KARAMANLI", City.builder().id(15L).build()),
                    new Region("KEMER", City.builder().id(15L).build()),
                    new Region("MERKEZ", City.builder().id(15L).build()),
                    new Region("TEFENNİ", City.builder().id(15L).build()),
                    new Region("YEŞİLOVA", City.builder().id(15L).build()),
                    new Region("BÜYÜKORHAN", City.builder().id(16L).build()),
                    new Region("GEMLİK", City.builder().id(16L).build()),
                    new Region("GÜRSU", City.builder().id(16L).build()),
                    new Region("HARMANCIK", City.builder().id(16L).build()),
                    new Region("İNEGÖL", City.builder().id(16L).build()),
                    new Region("İZNİK", City.builder().id(16L).build()),
                    new Region("KARACABEY", City.builder().id(16L).build()),
                    new Region("KELES", City.builder().id(16L).build()),
                    new Region("KESTEL", City.builder().id(16L).build()),
                    new Region("MUDANYA", City.builder().id(16L).build()),
                    new Region("MUSTAFAKEMALPAŞA", City.builder().id(16L).build()),
                    new Region("NİLÜFER", City.builder().id(16L).build()),
                    new Region("ORHANELİ", City.builder().id(16L).build()),
                    new Region("ORHANGAZİ", City.builder().id(16L).build()),
                    new Region("OSMANGAZİ", City.builder().id(16L).build()),
                    new Region("YENİŞEHİR", City.builder().id(16L).build()),
                    new Region("YILDIRIM", City.builder().id(16L).build()),
                    new Region("AYVACIK", City.builder().id(17L).build()),
                    new Region("BAYRAMİÇ", City.builder().id(17L).build()),
                    new Region("BİGA", City.builder().id(17L).build()),
                    new Region("BOZCAADA", City.builder().id(17L).build()),
                    new Region("ÇAN", City.builder().id(17L).build()),
                    new Region("ECEABAT", City.builder().id(17L).build()),
                    new Region("EZİNE", City.builder().id(17L).build()),
                    new Region("GELİBOLU", City.builder().id(17L).build()),
                    new Region("GÖKÇEADA", City.builder().id(17L).build()),
                    new Region("LAPSEKİ", City.builder().id(17L).build()),
                    new Region("MERKEZ", City.builder().id(17L).build()),
                    new Region("YENİCE", City.builder().id(17L).build()),
                    new Region("ATKARACALAR", City.builder().id(18L).build()),
                    new Region("BAYRAMÖREN", City.builder().id(18L).build()),
                    new Region("ÇERKEŞ", City.builder().id(18L).build()),
                    new Region("ELDİVAN", City.builder().id(18L).build()),
                    new Region("ILGAZ", City.builder().id(18L).build()),
                    new Region("KIZILIRMAK", City.builder().id(18L).build()),
                    new Region("KORGUN", City.builder().id(18L).build()),
                    new Region("KURŞUNLU", City.builder().id(18L).build()),
                    new Region("MERKEZ", City.builder().id(18L).build()),
                    new Region("ORTA", City.builder().id(18L).build()),
                    new Region("ŞABANÖZÜ", City.builder().id(18L).build()),
                    new Region("YAPRAKLI", City.builder().id(18L).build()),
                    new Region("ALACA", City.builder().id(19L).build()),
                    new Region("BAYAT", City.builder().id(19L).build()),
                    new Region("BOĞAZKALE", City.builder().id(19L).build()),
                    new Region("DODURGA", City.builder().id(19L).build()),
                    new Region("İSKİLİP", City.builder().id(19L).build()),
                    new Region("KARGI", City.builder().id(19L).build()),
                    new Region("LAÇİN", City.builder().id(19L).build()),
                    new Region("MECİTÖZÜ", City.builder().id(19L).build()),
                    new Region("MERKEZ", City.builder().id(19L).build()),
                    new Region("OĞUZLAR", City.builder().id(19L).build()),
                    new Region("ORTAKÖY", City.builder().id(19L).build()),
                    new Region("OSMANCIK", City.builder().id(19L).build()),
                    new Region("SUNGURLU", City.builder().id(19L).build()),
                    new Region("UĞURLUDAĞ", City.builder().id(19L).build()),
                    new Region("ACIPAYAM", City.builder().id(20L).build()),
                    new Region("BABADAĞ", City.builder().id(20L).build()),
                    new Region("BAKLAN", City.builder().id(20L).build()),
                    new Region("BEKİLLİ", City.builder().id(20L).build()),
                    new Region("BEYAĞAÇ", City.builder().id(20L).build()),
                    new Region("BOZKURT", City.builder().id(20L).build()),
                    new Region("BULDAN", City.builder().id(20L).build()),
                    new Region("ÇAL", City.builder().id(20L).build()),
                    new Region("ÇAMELİ", City.builder().id(20L).build()),
                    new Region("ÇARDAK", City.builder().id(20L).build()),
                    new Region("ÇİVRİL", City.builder().id(20L).build()),
                    new Region("GÜNEY", City.builder().id(20L).build()),
                    new Region("HONAZ", City.builder().id(20L).build()),
                    new Region("KALE", City.builder().id(20L).build()),
                    new Region("MERKEZEFENDİ", City.builder().id(20L).build()),
                    new Region("PAMUKKALE", City.builder().id(20L).build()),
                    new Region("SARAYKÖY", City.builder().id(20L).build()),
                    new Region("SERİNHİSAR", City.builder().id(20L).build()),
                    new Region("TAVAS", City.builder().id(20L).build()),
                    new Region("BAĞLAR", City.builder().id(21L).build()),
                    new Region("BİSMİL", City.builder().id(21L).build()),
                    new Region("ÇERMİK", City.builder().id(21L).build()),
                    new Region("ÇINAR", City.builder().id(21L).build()),
                    new Region("ÇÜNGÜŞ", City.builder().id(21L).build()),
                    new Region("DİCLE", City.builder().id(21L).build()),
                    new Region("EĞİL", City.builder().id(21L).build()),
                    new Region("ERGANİ", City.builder().id(21L).build()),
                    new Region("HANİ", City.builder().id(21L).build()),
                    new Region("HAZRO", City.builder().id(21L).build()),
                    new Region("KAYAPINAR", City.builder().id(21L).build()),
                    new Region("KOCAKÖY", City.builder().id(21L).build()),
                    new Region("KULP", City.builder().id(21L).build()),
                    new Region("LİCE", City.builder().id(21L).build()),
                    new Region("SİLVAN", City.builder().id(21L).build()),
                    new Region("SUR", City.builder().id(21L).build()),
                    new Region("YENİŞEHİR", City.builder().id(21L).build()),
                    new Region("ENEZ", City.builder().id(22L).build()),
                    new Region("HAVSA", City.builder().id(22L).build()),
                    new Region("İPSALA", City.builder().id(22L).build()),
                    new Region("KEŞAN", City.builder().id(22L).build()),
                    new Region("LALAPAŞA", City.builder().id(22L).build()),
                    new Region("MERİÇ", City.builder().id(22L).build()),
                    new Region("MERKEZ", City.builder().id(22L).build()),
                    new Region("SÜLOĞLU", City.builder().id(22L).build()),
                    new Region("UZUNKÖPRÜ", City.builder().id(22L).build()),
                    new Region("AĞIN", City.builder().id(23L).build()),
                    new Region("ALACAKAYA", City.builder().id(23L).build()),
                    new Region("ARICAK", City.builder().id(23L).build()),
                    new Region("BASKİL", City.builder().id(23L).build()),
                    new Region("KARAKOÇAN", City.builder().id(23L).build()),
                    new Region("KEBAN", City.builder().id(23L).build()),
                    new Region("KOVANCILAR", City.builder().id(23L).build()),
                    new Region("MADEN", City.builder().id(23L).build()),
                    new Region("MERKEZ", City.builder().id(23L).build()),
                    new Region("PALU", City.builder().id(23L).build()),
                    new Region("SİVRİCE", City.builder().id(23L).build()),
                    new Region("ÇAYIRLI", City.builder().id(24L).build()),
                    new Region("İLİÇ", City.builder().id(24L).build()),
                    new Region("KEMAH", City.builder().id(24L).build()),
                    new Region("KEMALİYE", City.builder().id(24L).build()),
                    new Region("MERKEZ", City.builder().id(24L).build()),
                    new Region("OTLUKBELİ", City.builder().id(24L).build()),
                    new Region("REFAHİYE", City.builder().id(24L).build()),
                    new Region("TERCAN", City.builder().id(24L).build()),
                    new Region("ÜZÜMLÜ", City.builder().id(24L).build()),
                    new Region("AŞKALE", City.builder().id(25L).build()),
                    new Region("AZİZİYE", City.builder().id(25L).build()),
                    new Region("ÇAT", City.builder().id(25L).build()),
                    new Region("HINIS", City.builder().id(25L).build()),
                    new Region("HORASAN", City.builder().id(25L).build()),
                    new Region("İSPİR", City.builder().id(25L).build()),
                    new Region("KARAÇOBAN", City.builder().id(25L).build()),
                    new Region("KARAYAZI", City.builder().id(25L).build()),
                    new Region("KÖPRÜKÖY", City.builder().id(25L).build()),
                    new Region("NARMAN", City.builder().id(25L).build()),
                    new Region("OLTU", City.builder().id(25L).build()),
                    new Region("OLUR", City.builder().id(25L).build()),
                    new Region("PALANDÖKEN", City.builder().id(25L).build()),
                    new Region("PASİNLER", City.builder().id(25L).build()),
                    new Region("PAZARYOLU", City.builder().id(25L).build()),
                    new Region("ŞENKAYA", City.builder().id(25L).build()),
                    new Region("TEKMAN", City.builder().id(25L).build()),
                    new Region("TORTUM", City.builder().id(25L).build()),
                    new Region("UZUNDERE", City.builder().id(25L).build()),
                    new Region("YAKUTİYE", City.builder().id(25L).build()),
                    new Region("ALPU", City.builder().id(26L).build()),
                    new Region("BEYLİKOVA", City.builder().id(26L).build()),
                    new Region("ÇİFTELER", City.builder().id(26L).build()),
                    new Region("GÜNYÜZÜ", City.builder().id(26L).build()),
                    new Region("HAN", City.builder().id(26L).build()),
                    new Region("İNÖNÜ", City.builder().id(26L).build()),
                    new Region("MAHMUDİYE", City.builder().id(26L).build()),
                    new Region("MİHALGAZİ", City.builder().id(26L).build()),
                    new Region("MİHALIÇÇIK", City.builder().id(26L).build()),
                    new Region("ODUNPAZARI", City.builder().id(26L).build()),
                    new Region("SARICAKAYA", City.builder().id(26L).build()),
                    new Region("SEYİTGAZİ", City.builder().id(26L).build()),
                    new Region("SİVRİHİSAR", City.builder().id(26L).build()),
                    new Region("TEPEBAŞI", City.builder().id(26L).build()),
                    new Region("ARABAN", City.builder().id(27L).build()),
                    new Region("İSLAHİYE", City.builder().id(27L).build()),
                    new Region("KARKAMIŞ", City.builder().id(27L).build()),
                    new Region("NİZİP", City.builder().id(27L).build()),
                    new Region("NURDAĞI", City.builder().id(27L).build()),
                    new Region("OĞUZELİ", City.builder().id(27L).build()),
                    new Region("ŞAHİNBEY", City.builder().id(27L).build()),
                    new Region("ŞEHİTKAMİL", City.builder().id(27L).build()),
                    new Region("YAVUZELİ", City.builder().id(27L).build()),
                    new Region("ALUCRA", City.builder().id(28L).build()),
                    new Region("BULANCAK", City.builder().id(28L).build()),
                    new Region("ÇAMOLUK", City.builder().id(28L).build()),
                    new Region("ÇANAKÇI", City.builder().id(28L).build()),
                    new Region("DERELİ", City.builder().id(28L).build()),
                    new Region("DOĞANKENT", City.builder().id(28L).build()),
                    new Region("ESPİYE", City.builder().id(28L).build()),
                    new Region("EYNESİL", City.builder().id(28L).build()),
                    new Region("GÖRELE", City.builder().id(28L).build()),
                    new Region("GÜCE", City.builder().id(28L).build()),
                    new Region("KEŞAP", City.builder().id(28L).build()),
                    new Region("MERKEZ", City.builder().id(28L).build()),
                    new Region("PİRAZİZ", City.builder().id(28L).build()),
                    new Region("ŞEBİNKARAHİSAR", City.builder().id(28L).build()),
                    new Region("TİREBOLU", City.builder().id(28L).build()),
                    new Region("YAĞLIDERE", City.builder().id(28L).build()),
                    new Region("KELKİT", City.builder().id(29L).build()),
                    new Region("KÖSE", City.builder().id(29L).build()),
                    new Region("KÜRTÜN", City.builder().id(29L).build()),
                    new Region("MERKEZ", City.builder().id(29L).build()),
                    new Region("ŞİRAN", City.builder().id(29L).build()),
                    new Region("TORUL", City.builder().id(29L).build()),
                    new Region("ÇUKURCA", City.builder().id(30L).build()),
                    new Region("DERECİK", City.builder().id(30L).build()),
                    new Region("MERKEZ", City.builder().id(30L).build()),
                    new Region("ŞEMDİNLİ", City.builder().id(30L).build()),
                    new Region("YÜKSEKOVA", City.builder().id(30L).build()),
                    new Region("ALTINÖZÜ", City.builder().id(31L).build()),
                    new Region("ANTAKYA", City.builder().id(31L).build()),
                    new Region("ARSUZ", City.builder().id(31L).build()),
                    new Region("BELEN", City.builder().id(31L).build()),
                    new Region("DEFNE", City.builder().id(31L).build()),
                    new Region("DÖRTYOL", City.builder().id(31L).build()),
                    new Region("ERZİN", City.builder().id(31L).build()),
                    new Region("HASSA", City.builder().id(31L).build()),
                    new Region("İSKENDERUN", City.builder().id(31L).build()),
                    new Region("KIRIKHAN", City.builder().id(31L).build()),
                    new Region("KUMLU", City.builder().id(31L).build()),
                    new Region("PAYAS", City.builder().id(31L).build()),
                    new Region("REYHANLI", City.builder().id(31L).build()),
                    new Region("SAMANDAĞ", City.builder().id(31L).build()),
                    new Region("YAYLADAĞI", City.builder().id(31L).build()),
                    new Region("AKSU", City.builder().id(32L).build()),
                    new Region("ATABEY", City.builder().id(32L).build()),
                    new Region("EĞİRDİR", City.builder().id(32L).build()),
                    new Region("GELENDOST", City.builder().id(32L).build()),
                    new Region("GÖNEN", City.builder().id(32L).build()),
                    new Region("KEÇİBORLU", City.builder().id(32L).build()),
                    new Region("MERKEZ", City.builder().id(32L).build()),
                    new Region("SENİRKENT", City.builder().id(32L).build()),
                    new Region("SÜTÇÜLER", City.builder().id(32L).build()),
                    new Region("ŞARKİKARAAĞAÇ", City.builder().id(32L).build()),
                    new Region("ULUBORLU", City.builder().id(32L).build()),
                    new Region("YALVAÇ", City.builder().id(32L).build()),
                    new Region("YENİŞARBADEMLİ", City.builder().id(32L).build()),
                    new Region("AKDENİZ", City.builder().id(33L).build()),
                    new Region("ANAMUR", City.builder().id(33L).build()),
                    new Region("AYDINCIK", City.builder().id(33L).build()),
                    new Region("BOZYAZI", City.builder().id(33L).build()),
                    new Region("ÇAMLIYAYLA", City.builder().id(33L).build()),
                    new Region("ERDEMLİ", City.builder().id(33L).build()),
                    new Region("GÜLNAR", City.builder().id(33L).build()),
                    new Region("MEZİTLİ", City.builder().id(33L).build()),
                    new Region("MUT", City.builder().id(33L).build()),
                    new Region("SİLİFKE", City.builder().id(33L).build()),
                    new Region("TARSUS", City.builder().id(33L).build()),
                    new Region("TOROSLAR", City.builder().id(33L).build()),
                    new Region("YENİŞEHİR", City.builder().id(33L).build()),
                    new Region("ADALAR", City.builder().id(34L).build()),
                    new Region("ARNAVUTKÖY", City.builder().id(34L).build()),
                    new Region("ATAŞEHİR", City.builder().id(34L).build()),
                    new Region("AVCILAR", City.builder().id(34L).build()),
                    new Region("BAĞCILAR", City.builder().id(34L).build()),
                    new Region("BAHÇELİEVLER", City.builder().id(34L).build()),
                    new Region("BAKIRKÖY", City.builder().id(34L).build()),
                    new Region("BAŞAKŞEHİR", City.builder().id(34L).build()),
                    new Region("BAYRAMPAŞA", City.builder().id(34L).build()),
                    new Region("BEŞİKTAŞ", City.builder().id(34L).build()),
                    new Region("BEYKOZ", City.builder().id(34L).build()),
                    new Region("BEYLİKDÜZÜ", City.builder().id(34L).build()),
                    new Region("BEYOĞLU", City.builder().id(34L).build()),
                    new Region("BÜYÜKÇEKMECE", City.builder().id(34L).build()),
                    new Region("ÇATALCA", City.builder().id(34L).build()),
                    new Region("ÇEKMEKÖY", City.builder().id(34L).build()),
                    new Region("ESENLER", City.builder().id(34L).build()),
                    new Region("ESENYURT", City.builder().id(34L).build()),
                    new Region("EYÜPSULTAN", City.builder().id(34L).build()),
                    new Region("FATİH", City.builder().id(34L).build()),
                    new Region("GAZİOSMANPAŞA", City.builder().id(34L).build()),
                    new Region("GÜNGÖREN", City.builder().id(34L).build()),
                    new Region("KADIKÖY", City.builder().id(34L).build()),
                    new Region("KAĞITHANE", City.builder().id(34L).build()),
                    new Region("KARTAL", City.builder().id(34L).build()),
                    new Region("KÜÇÜKÇEKMECE", City.builder().id(34L).build()),
                    new Region("MALTEPE", City.builder().id(34L).build()),
                    new Region("PENDİK", City.builder().id(34L).build()),
                    new Region("SANCAKTEPE", City.builder().id(34L).build()),
                    new Region("SARIYER", City.builder().id(34L).build()),
                    new Region("SİLİVRİ", City.builder().id(34L).build()),
                    new Region("SULTANBEYLİ", City.builder().id(34L).build()),
                    new Region("SULTANGAZİ", City.builder().id(34L).build()),
                    new Region("ŞİLE", City.builder().id(34L).build()),
                    new Region("ŞİŞLİ", City.builder().id(34L).build()),
                    new Region("TUZLA", City.builder().id(34L).build()),
                    new Region("ÜMRANİYE", City.builder().id(34L).build()),
                    new Region("ÜSKÜDAR", City.builder().id(34L).build()),
                    new Region("ZEYTİNBURNU", City.builder().id(34L).build()),
                    new Region("ALİAĞA", City.builder().id(35L).build()),
                    new Region("BALÇOVA", City.builder().id(35L).build()),
                    new Region("BAYINDIR", City.builder().id(35L).build()),
                    new Region("BAYRAKLI", City.builder().id(35L).build()),
                    new Region("BERGAMA", City.builder().id(35L).build()),
                    new Region("BEYDAĞ", City.builder().id(35L).build()),
                    new Region("BORNOVA", City.builder().id(35L).build()),
                    new Region("BUCA", City.builder().id(35L).build()),
                    new Region("ÇEŞME", City.builder().id(35L).build()),
                    new Region("ÇİĞLİ", City.builder().id(35L).build()),
                    new Region("DİKİLİ", City.builder().id(35L).build()),
                    new Region("FOÇA", City.builder().id(35L).build()),
                    new Region("GAZİEMİR", City.builder().id(35L).build()),
                    new Region("GÜZELBAHÇE", City.builder().id(35L).build()),
                    new Region("KARABAĞLAR", City.builder().id(35L).build()),
                    new Region("KARABURUN", City.builder().id(35L).build()),
                    new Region("KARŞIYAKA", City.builder().id(35L).build()),
                    new Region("KEMALPAŞA", City.builder().id(35L).build()),
                    new Region("KINIK", City.builder().id(35L).build()),
                    new Region("KİRAZ", City.builder().id(35L).build()),
                    new Region("KONAK", City.builder().id(35L).build()),
                    new Region("MENDERES", City.builder().id(35L).build()),
                    new Region("MENEMEN", City.builder().id(35L).build()),
                    new Region("NARLIDERE", City.builder().id(35L).build()),
                    new Region("ÖDEMİŞ", City.builder().id(35L).build()),
                    new Region("SEFERİHİSAR", City.builder().id(35L).build()),
                    new Region("SELÇUK", City.builder().id(35L).build()),
                    new Region("TİRE", City.builder().id(35L).build()),
                    new Region("TORBALI", City.builder().id(35L).build()),
                    new Region("URLA", City.builder().id(35L).build()),
                    new Region("AKYAKA", City.builder().id(36L).build()),
                    new Region("ARPAÇAY", City.builder().id(36L).build()),
                    new Region("DİGOR", City.builder().id(36L).build()),
                    new Region("KAĞIZMAN", City.builder().id(36L).build()),
                    new Region("MERKEZ", City.builder().id(36L).build()),
                    new Region("SARIKAMIŞ", City.builder().id(36L).build()),
                    new Region("SELİM", City.builder().id(36L).build()),
                    new Region("SUSUZ", City.builder().id(36L).build()),
                    new Region("ABANA", City.builder().id(37L).build()),
                    new Region("AĞLI", City.builder().id(37L).build()),
                    new Region("ARAÇ", City.builder().id(37L).build()),
                    new Region("AZDAVAY", City.builder().id(37L).build()),
                    new Region("BOZKURT", City.builder().id(37L).build()),
                    new Region("CİDE", City.builder().id(37L).build()),
                    new Region("ÇATALZEYTİN", City.builder().id(37L).build()),
                    new Region("DADAY", City.builder().id(37L).build()),
                    new Region("DEVREKANİ", City.builder().id(37L).build()),
                    new Region("DOĞANYURT", City.builder().id(37L).build()),
                    new Region("HANÖNÜ", City.builder().id(37L).build()),
                    new Region("İHSANGAZİ", City.builder().id(37L).build()),
                    new Region("İNEBOLU", City.builder().id(37L).build()),
                    new Region("KÜRE", City.builder().id(37L).build()),
                    new Region("MERKEZ", City.builder().id(37L).build()),
                    new Region("PINARBAŞI", City.builder().id(37L).build()),
                    new Region("SEYDİLER", City.builder().id(37L).build()),
                    new Region("ŞENPAZAR", City.builder().id(37L).build()),
                    new Region("TAŞKÖPRÜ", City.builder().id(37L).build()),
                    new Region("TOSYA", City.builder().id(37L).build()),
                    new Region("AKKIŞLA", City.builder().id(38L).build()),
                    new Region("BÜNYAN", City.builder().id(38L).build()),
                    new Region("DEVELİ", City.builder().id(38L).build()),
                    new Region("FELAHİYE", City.builder().id(38L).build()),
                    new Region("HACILAR", City.builder().id(38L).build()),
                    new Region("İNCESU", City.builder().id(38L).build()),
                    new Region("KOCASİNAN", City.builder().id(38L).build()),
                    new Region("MELİKGAZİ", City.builder().id(38L).build()),
                    new Region("ÖZVATAN", City.builder().id(38L).build()),
                    new Region("PINARBAŞI", City.builder().id(38L).build()),
                    new Region("SARIOĞLAN", City.builder().id(38L).build()),
                    new Region("SARIZ", City.builder().id(38L).build()),
                    new Region("TALAS", City.builder().id(38L).build()),
                    new Region("TOMARZA", City.builder().id(38L).build()),
                    new Region("YAHYALI", City.builder().id(38L).build()),
                    new Region("YEŞİLHİSAR", City.builder().id(38L).build()),
                    new Region("BABAESKİ", City.builder().id(39L).build()),
                    new Region("DEMİRKÖY", City.builder().id(39L).build()),
                    new Region("KOFÇAZ", City.builder().id(39L).build()),
                    new Region("LÜLEBURGAZ", City.builder().id(39L).build()),
                    new Region("MERKEZ", City.builder().id(39L).build()),
                    new Region("PEHLİVANKÖY", City.builder().id(39L).build()),
                    new Region("PINARHİSAR", City.builder().id(39L).build()),
                    new Region("VİZE", City.builder().id(39L).build()),
                    new Region("AKÇAKENT", City.builder().id(40L).build()),
                    new Region("AKPINAR", City.builder().id(40L).build()),
                    new Region("BOZTEPE", City.builder().id(40L).build()),
                    new Region("ÇİÇEKDAĞI", City.builder().id(40L).build()),
                    new Region("KAMAN", City.builder().id(40L).build()),
                    new Region("MERKEZ", City.builder().id(40L).build()),
                    new Region("MUCUR", City.builder().id(40L).build()),
                    new Region("BAŞİSKELE", City.builder().id(41L).build()),
                    new Region("ÇAYIROVA", City.builder().id(41L).build()),
                    new Region("DARICA", City.builder().id(41L).build()),
                    new Region("DERİNCE", City.builder().id(41L).build()),
                    new Region("DİLOVASI", City.builder().id(41L).build()),
                    new Region("GEBZE", City.builder().id(41L).build()),
                    new Region("GÖLCÜK", City.builder().id(41L).build()),
                    new Region("İZMİT", City.builder().id(41L).build()),
                    new Region("KANDIRA", City.builder().id(41L).build()),
                    new Region("KARAMÜRSEL", City.builder().id(41L).build()),
                    new Region("KARTEPE", City.builder().id(41L).build()),
                    new Region("KÖRFEZ", City.builder().id(41L).build()),
                    new Region("AHIRLI", City.builder().id(42L).build()),
                    new Region("AKÖREN", City.builder().id(42L).build()),
                    new Region("AKŞEHİR", City.builder().id(42L).build()),
                    new Region("ALTINEKİN", City.builder().id(42L).build()),
                    new Region("BEYŞEHİR", City.builder().id(42L).build()),
                    new Region("BOZKIR", City.builder().id(42L).build()),
                    new Region("CİHANBEYLİ", City.builder().id(42L).build()),
                    new Region("ÇELTİK", City.builder().id(42L).build()),
                    new Region("ÇUMRA", City.builder().id(42L).build()),
                    new Region("DERBENT", City.builder().id(42L).build()),
                    new Region("DEREBUCAK", City.builder().id(42L).build()),
                    new Region("DOĞANHİSAR", City.builder().id(42L).build()),
                    new Region("EMİRGAZİ", City.builder().id(42L).build()),
                    new Region("EREĞLİ", City.builder().id(42L).build()),
                    new Region("GÜNEYSINIR", City.builder().id(42L).build()),
                    new Region("HADİM", City.builder().id(42L).build()),
                    new Region("HALKAPINAR", City.builder().id(42L).build()),
                    new Region("HÜYÜK", City.builder().id(42L).build()),
                    new Region("ILGIN", City.builder().id(42L).build()),
                    new Region("KADINHANI", City.builder().id(42L).build()),
                    new Region("KARAPINAR", City.builder().id(42L).build()),
                    new Region("KARATAY", City.builder().id(42L).build()),
                    new Region("KULU", City.builder().id(42L).build()),
                    new Region("MERAM", City.builder().id(42L).build()),
                    new Region("SARAYÖNÜ", City.builder().id(42L).build()),
                    new Region("SELÇUKLU", City.builder().id(42L).build()),
                    new Region("SEYDİŞEHİR", City.builder().id(42L).build()),
                    new Region("TAŞKENT", City.builder().id(42L).build()),
                    new Region("TUZLUKÇU", City.builder().id(42L).build()),
                    new Region("YALIHÜYÜK", City.builder().id(42L).build()),
                    new Region("YUNAK", City.builder().id(42L).build()),
                    new Region("ALTINTAŞ", City.builder().id(43L).build()),
                    new Region("ASLANAPA", City.builder().id(43L).build()),
                    new Region("ÇAVDARHİSAR", City.builder().id(43L).build()),
                    new Region("DOMANİÇ", City.builder().id(43L).build()),
                    new Region("DUMLUPINAR", City.builder().id(43L).build()),
                    new Region("EMET", City.builder().id(43L).build()),
                    new Region("GEDİZ", City.builder().id(43L).build()),
                    new Region("HİSARCIK", City.builder().id(43L).build()),
                    new Region("MERKEZ", City.builder().id(43L).build()),
                    new Region("PAZARLAR", City.builder().id(43L).build()),
                    new Region("SİMAV", City.builder().id(43L).build()),
                    new Region("ŞAPHANE", City.builder().id(43L).build()),
                    new Region("TAVŞANLI", City.builder().id(43L).build()),
                    new Region("AKÇADAĞ", City.builder().id(44L).build()),
                    new Region("ARAPGİR", City.builder().id(44L).build()),
                    new Region("ARGUVAN", City.builder().id(44L).build()),
                    new Region("BATTALGAZİ", City.builder().id(44L).build()),
                    new Region("DARENDE", City.builder().id(44L).build()),
                    new Region("DOĞANŞEHİR", City.builder().id(44L).build()),
                    new Region("DOĞANYOL", City.builder().id(44L).build()),
                    new Region("HEKİMHAN", City.builder().id(44L).build()),
                    new Region("KALE", City.builder().id(44L).build()),
                    new Region("KULUNCAK", City.builder().id(44L).build()),
                    new Region("PÜTÜRGE", City.builder().id(44L).build()),
                    new Region("YAZIHAN", City.builder().id(44L).build()),
                    new Region("YEŞİLYURT", City.builder().id(44L).build()),
                    new Region("AHMETLİ", City.builder().id(45L).build()),
                    new Region("AKHİSAR", City.builder().id(45L).build()),
                    new Region("ALAŞEHİR", City.builder().id(45L).build()),
                    new Region("DEMİRCİ", City.builder().id(45L).build()),
                    new Region("GÖLMARMARA", City.builder().id(45L).build()),
                    new Region("GÖRDES", City.builder().id(45L).build()),
                    new Region("KIRKAĞAÇ", City.builder().id(45L).build()),
                    new Region("KÖPRÜBAŞI", City.builder().id(45L).build()),
                    new Region("KULA", City.builder().id(45L).build()),
                    new Region("SALİHLİ", City.builder().id(45L).build()),
                    new Region("SARIGÖL", City.builder().id(45L).build()),
                    new Region("SARUHANLI", City.builder().id(45L).build()),
                    new Region("SELENDİ", City.builder().id(45L).build()),
                    new Region("SOMA", City.builder().id(45L).build()),
                    new Region("ŞEHZADELER", City.builder().id(45L).build()),
                    new Region("TURGUTLU", City.builder().id(45L).build()),
                    new Region("YUNUSEMRE", City.builder().id(45L).build()),
                    new Region("AFŞİN", City.builder().id(46L).build()),
                    new Region("ANDIRIN", City.builder().id(46L).build()),
                    new Region("ÇAĞLAYANCERİT", City.builder().id(46L).build()),
                    new Region("DULKADİROĞLU", City.builder().id(46L).build()),
                    new Region("EKİNÖZÜ", City.builder().id(46L).build()),
                    new Region("ELBİSTAN", City.builder().id(46L).build()),
                    new Region("GÖKSUN", City.builder().id(46L).build()),
                    new Region("NURHAK", City.builder().id(46L).build()),
                    new Region("ONİKİŞUBAT", City.builder().id(46L).build()),
                    new Region("PAZARCIK", City.builder().id(46L).build()),
                    new Region("TÜRKOĞLU", City.builder().id(46L).build()),
                    new Region("ARTUKLU", City.builder().id(47L).build()),
                    new Region("DARGEÇİT", City.builder().id(47L).build()),
                    new Region("DERİK", City.builder().id(47L).build()),
                    new Region("KIZILTEPE", City.builder().id(47L).build()),
                    new Region("MAZIDAĞI", City.builder().id(47L).build()),
                    new Region("MİDYAT", City.builder().id(47L).build()),
                    new Region("NUSAYBİN", City.builder().id(47L).build()),
                    new Region("ÖMERLİ", City.builder().id(47L).build()),
                    new Region("SAVUR", City.builder().id(47L).build()),
                    new Region("YEŞİLLİ", City.builder().id(47L).build()),
                    new Region("BODRUM", City.builder().id(48L).build()),
                    new Region("DALAMAN", City.builder().id(48L).build()),
                    new Region("DATÇA", City.builder().id(48L).build()),
                    new Region("FETHİYE", City.builder().id(48L).build()),
                    new Region("KAVAKLIDERE", City.builder().id(48L).build()),
                    new Region("KÖYCEĞİZ", City.builder().id(48L).build()),
                    new Region("MARMARİS", City.builder().id(48L).build()),
                    new Region("MENTEŞE", City.builder().id(48L).build()),
                    new Region("MİLAS", City.builder().id(48L).build()),
                    new Region("ORTACA", City.builder().id(48L).build()),
                    new Region("SEYDİKEMER", City.builder().id(48L).build()),
                    new Region("ULA", City.builder().id(48L).build()),
                    new Region("YATAĞAN", City.builder().id(48L).build()),
                    new Region("BULANIK", City.builder().id(49L).build()),
                    new Region("HASKÖY", City.builder().id(49L).build()),
                    new Region("KORKUT", City.builder().id(49L).build()),
                    new Region("MALAZGİRT", City.builder().id(49L).build()),
                    new Region("MERKEZ", City.builder().id(49L).build()),
                    new Region("VARTO", City.builder().id(49L).build()),
                    new Region("ACIGÖL", City.builder().id(50L).build()),
                    new Region("AVANOS", City.builder().id(50L).build()),
                    new Region("DERİNKUYU", City.builder().id(50L).build()),
                    new Region("GÜLŞEHİR", City.builder().id(50L).build()),
                    new Region("HACIBEKTAŞ", City.builder().id(50L).build()),
                    new Region("KOZAKLI", City.builder().id(50L).build()),
                    new Region("MERKEZ", City.builder().id(50L).build()),
                    new Region("ÜRGÜP", City.builder().id(50L).build()),
                    new Region("ALTUNHİSAR", City.builder().id(51L).build()),
                    new Region("BOR", City.builder().id(51L).build()),
                    new Region("ÇAMARDI", City.builder().id(51L).build()),
                    new Region("ÇİFTLİK", City.builder().id(51L).build()),
                    new Region("MERKEZ", City.builder().id(51L).build()),
                    new Region("ULUKIŞLA", City.builder().id(51L).build()),
                    new Region("AKKUŞ", City.builder().id(52L).build()),
                    new Region("ALTINORDU", City.builder().id(52L).build()),
                    new Region("AYBASTI", City.builder().id(52L).build()),
                    new Region("ÇAMAŞ", City.builder().id(52L).build()),
                    new Region("ÇATALPINAR", City.builder().id(52L).build()),
                    new Region("ÇAYBAŞI", City.builder().id(52L).build()),
                    new Region("FATSA", City.builder().id(52L).build()),
                    new Region("GÖLKÖY", City.builder().id(52L).build()),
                    new Region("GÜLYALI", City.builder().id(52L).build()),
                    new Region("GÜRGENTEPE", City.builder().id(52L).build()),
                    new Region("İKİZCE", City.builder().id(52L).build()),
                    new Region("KABADÜZ", City.builder().id(52L).build()),
                    new Region("KABATAŞ", City.builder().id(52L).build()),
                    new Region("KORGAN", City.builder().id(52L).build()),
                    new Region("KUMRU", City.builder().id(52L).build()),
                    new Region("MESUDİYE", City.builder().id(52L).build()),
                    new Region("PERŞEMBE", City.builder().id(52L).build()),
                    new Region("ULUBEY", City.builder().id(52L).build()),
                    new Region("ÜNYE", City.builder().id(52L).build()),
                    new Region("ARDEŞEN", City.builder().id(53L).build()),
                    new Region("ÇAMLIHEMŞİN", City.builder().id(53L).build()),
                    new Region("ÇAYELİ", City.builder().id(53L).build()),
                    new Region("DEREPAZARI", City.builder().id(53L).build()),
                    new Region("FINDIKLI", City.builder().id(53L).build()),
                    new Region("GÜNEYSU", City.builder().id(53L).build()),
                    new Region("HEMŞİN", City.builder().id(53L).build()),
                    new Region("İKİZDERE", City.builder().id(53L).build()),
                    new Region("İYİDERE", City.builder().id(53L).build()),
                    new Region("KALKANDERE", City.builder().id(53L).build()),
                    new Region("MERKEZ", City.builder().id(53L).build()),
                    new Region("PAZAR", City.builder().id(53L).build()),
                    new Region("ADAPAZARI", City.builder().id(54L).build()),
                    new Region("AKYAZI", City.builder().id(54L).build()),
                    new Region("ARİFİYE", City.builder().id(54L).build()),
                    new Region("ERENLER", City.builder().id(54L).build()),
                    new Region("FERİZLİ", City.builder().id(54L).build()),
                    new Region("GEYVE", City.builder().id(54L).build()),
                    new Region("HENDEK", City.builder().id(54L).build()),
                    new Region("KARAPÜRÇEK", City.builder().id(54L).build()),
                    new Region("KARASU", City.builder().id(54L).build()),
                    new Region("KAYNARCA", City.builder().id(54L).build()),
                    new Region("KOCAALİ", City.builder().id(54L).build()),
                    new Region("PAMUKOVA", City.builder().id(54L).build()),
                    new Region("SAPANCA", City.builder().id(54L).build()),
                    new Region("SERDİVAN", City.builder().id(54L).build()),
                    new Region("SÖĞÜTLÜ", City.builder().id(54L).build()),
                    new Region("TARAKLI", City.builder().id(54L).build()),
                    new Region("ALAÇAM", City.builder().id(55L).build()),
                    new Region("ASARCIK", City.builder().id(55L).build()),
                    new Region("ATAKUM", City.builder().id(55L).build()),
                    new Region("AYVACIK", City.builder().id(55L).build()),
                    new Region("BAFRA", City.builder().id(55L).build()),
                    new Region("CANİK", City.builder().id(55L).build()),
                    new Region("ÇARŞAMBA", City.builder().id(55L).build()),
                    new Region("HAVZA", City.builder().id(55L).build()),
                    new Region("İLKADIM", City.builder().id(55L).build()),
                    new Region("KAVAK", City.builder().id(55L).build()),
                    new Region("LADİK", City.builder().id(55L).build()),
                    new Region("SALIPAZARI", City.builder().id(55L).build()),
                    new Region("TEKKEKÖY", City.builder().id(55L).build()),
                    new Region("TERME", City.builder().id(55L).build()),
                    new Region("VEZİRKÖPRÜ", City.builder().id(55L).build()),
                    new Region("YAKAKENT", City.builder().id(55L).build()),
                    new Region("19 MAYIS", City.builder().id(55L).build()),
                    new Region("BAYKAN", City.builder().id(56L).build()),
                    new Region("ERUH", City.builder().id(56L).build()),
                    new Region("KURTALAN", City.builder().id(56L).build()),
                    new Region("MERKEZ", City.builder().id(56L).build()),
                    new Region("PERVARİ", City.builder().id(56L).build()),
                    new Region("ŞİRVAN", City.builder().id(56L).build()),
                    new Region("TİLLO", City.builder().id(56L).build()),
                    new Region("AYANCIK", City.builder().id(57L).build()),
                    new Region("BOYABAT", City.builder().id(57L).build()),
                    new Region("DİKMEN", City.builder().id(57L).build()),
                    new Region("DURAĞAN", City.builder().id(57L).build()),
                    new Region("ERFELEK", City.builder().id(57L).build()),
                    new Region("GERZE", City.builder().id(57L).build()),
                    new Region("MERKEZ", City.builder().id(57L).build()),
                    new Region("SARAYDÜZÜ", City.builder().id(57L).build()),
                    new Region("TÜRKELİ", City.builder().id(57L).build()),
                    new Region("AKINCILAR", City.builder().id(58L).build()),
                    new Region("ALTINYAYLA", City.builder().id(58L).build()),
                    new Region("DİVRİĞİ", City.builder().id(58L).build()),
                    new Region("DOĞANŞAR", City.builder().id(58L).build()),
                    new Region("GEMEREK", City.builder().id(58L).build()),
                    new Region("GÖLOVA", City.builder().id(58L).build()),
                    new Region("GÜRÜN", City.builder().id(58L).build()),
                    new Region("HAFİK", City.builder().id(58L).build()),
                    new Region("İMRANLI", City.builder().id(58L).build()),
                    new Region("KANGAL", City.builder().id(58L).build()),
                    new Region("KOYULHİSAR", City.builder().id(58L).build()),
                    new Region("MERKEZ", City.builder().id(58L).build()),
                    new Region("SUŞEHRİ", City.builder().id(58L).build()),
                    new Region("ŞARKIŞLA", City.builder().id(58L).build()),
                    new Region("ULAŞ", City.builder().id(58L).build()),
                    new Region("YILDIZELİ", City.builder().id(58L).build()),
                    new Region("ZARA", City.builder().id(58L).build()),
                    new Region("ÇERKEZKÖY", City.builder().id(59L).build()),
                    new Region("ÇORLU", City.builder().id(59L).build()),
                    new Region("ERGENE", City.builder().id(59L).build()),
                    new Region("HAYRABOLU", City.builder().id(59L).build()),
                    new Region("KAPAKLI", City.builder().id(59L).build()),
                    new Region("MALKARA", City.builder().id(59L).build()),
                    new Region("MARMARAEREĞLİSİ", City.builder().id(59L).build()),
                    new Region("MURATLI", City.builder().id(59L).build()),
                    new Region("SARAY", City.builder().id(59L).build()),
                    new Region("SÜLEYMANPAŞA", City.builder().id(59L).build()),
                    new Region("ŞARKÖY", City.builder().id(59L).build()),
                    new Region("ALMUS", City.builder().id(60L).build()),
                    new Region("ARTOVA", City.builder().id(60L).build()),
                    new Region("BAŞÇİFTLİK", City.builder().id(60L).build()),
                    new Region("ERBAA", City.builder().id(60L).build()),
                    new Region("MERKEZ", City.builder().id(60L).build()),
                    new Region("NİKSAR", City.builder().id(60L).build()),
                    new Region("PAZAR", City.builder().id(60L).build()),
                    new Region("REŞADİYE", City.builder().id(60L).build()),
                    new Region("SULUSARAY", City.builder().id(60L).build()),
                    new Region("TURHAL", City.builder().id(60L).build()),
                    new Region("YEŞİLYURT", City.builder().id(60L).build()),
                    new Region("ZİLE", City.builder().id(60L).build()),
                    new Region("AKÇAABAT", City.builder().id(61L).build()),
                    new Region("ARAKLI", City.builder().id(61L).build()),
                    new Region("ARSİN", City.builder().id(61L).build()),
                    new Region("BEŞİKDÜZÜ", City.builder().id(61L).build()),
                    new Region("ÇARŞIBAŞI", City.builder().id(61L).build()),
                    new Region("ÇAYKARA", City.builder().id(61L).build()),
                    new Region("DERNEKPAZARI", City.builder().id(61L).build()),
                    new Region("DÜZKÖY", City.builder().id(61L).build()),
                    new Region("HAYRAT", City.builder().id(61L).build()),
                    new Region("KÖPRÜBAŞI", City.builder().id(61L).build()),
                    new Region("MAÇKA", City.builder().id(61L).build()),
                    new Region("OF", City.builder().id(61L).build()),
                    new Region("ORTAHİSAR", City.builder().id(61L).build()),
                    new Region("SÜRMENE", City.builder().id(61L).build()),
                    new Region("ŞALPAZARI", City.builder().id(61L).build()),
                    new Region("TONYA", City.builder().id(61L).build()),
                    new Region("VAKFIKEBİR", City.builder().id(61L).build()),
                    new Region("YOMRA", City.builder().id(61L).build()),
                    new Region("ÇEMİŞGEZEK", City.builder().id(62L).build()),
                    new Region("HOZAT", City.builder().id(62L).build()),
                    new Region("MAZGİRT", City.builder().id(62L).build()),
                    new Region("MERKEZ", City.builder().id(62L).build()),
                    new Region("NAZIMİYE", City.builder().id(62L).build()),
                    new Region("OVACIK", City.builder().id(62L).build()),
                    new Region("PERTEK", City.builder().id(62L).build()),
                    new Region("PÜLÜMÜR", City.builder().id(62L).build()),
                    new Region("AKÇAKALE", City.builder().id(63L).build()),
                    new Region("BİRECİK", City.builder().id(63L).build()),
                    new Region("BOZOVA", City.builder().id(63L).build()),
                    new Region("CEYLANPINAR", City.builder().id(63L).build()),
                    new Region("EYYÜBİYE", City.builder().id(63L).build()),
                    new Region("HALFETİ", City.builder().id(63L).build()),
                    new Region("HALİLİYE", City.builder().id(63L).build()),
                    new Region("HARRAN", City.builder().id(63L).build()),
                    new Region("HİLVAN", City.builder().id(63L).build()),
                    new Region("KARAKÖPRÜ", City.builder().id(63L).build()),
                    new Region("SİVEREK", City.builder().id(63L).build()),
                    new Region("SURUÇ", City.builder().id(63L).build()),
                    new Region("VİRANŞEHİR", City.builder().id(63L).build()),
                    new Region("BANAZ", City.builder().id(64L).build()),
                    new Region("EŞME", City.builder().id(64L).build()),
                    new Region("KARAHALLI", City.builder().id(64L).build()),
                    new Region("MERKEZ", City.builder().id(64L).build()),
                    new Region("SİVASLI", City.builder().id(64L).build()),
                    new Region("ULUBEY", City.builder().id(64L).build()),
                    new Region("BAHÇESARAY", City.builder().id(65L).build()),
                    new Region("BAŞKALE", City.builder().id(65L).build()),
                    new Region("ÇALDIRAN", City.builder().id(65L).build()),
                    new Region("ÇATAK", City.builder().id(65L).build()),
                    new Region("EDREMİT", City.builder().id(65L).build()),
                    new Region("ERCİŞ", City.builder().id(65L).build()),
                    new Region("GEVAŞ", City.builder().id(65L).build()),
                    new Region("GÜRPINAR", City.builder().id(65L).build()),
                    new Region("İPEKYOLU", City.builder().id(65L).build()),
                    new Region("MURADİYE", City.builder().id(65L).build()),
                    new Region("ÖZALP", City.builder().id(65L).build()),
                    new Region("SARAY", City.builder().id(65L).build()),
                    new Region("TUŞBA", City.builder().id(65L).build()),
                    new Region("AKDAĞMADENİ", City.builder().id(66L).build()),
                    new Region("AYDINCIK", City.builder().id(66L).build()),
                    new Region("BOĞAZLIYAN", City.builder().id(66L).build()),
                    new Region("ÇANDIR", City.builder().id(66L).build()),
                    new Region("ÇAYIRALAN", City.builder().id(66L).build()),
                    new Region("ÇEKEREK", City.builder().id(66L).build()),
                    new Region("KADIŞEHRİ", City.builder().id(66L).build()),
                    new Region("MERKEZ", City.builder().id(66L).build()),
                    new Region("SARAYKENT", City.builder().id(66L).build()),
                    new Region("SARIKAYA", City.builder().id(66L).build()),
                    new Region("SORGUN", City.builder().id(66L).build()),
                    new Region("ŞEFAATLİ", City.builder().id(66L).build()),
                    new Region("YENİFAKILI", City.builder().id(66L).build()),
                    new Region("YERKÖY", City.builder().id(66L).build()),
                    new Region("ALAPLI", City.builder().id(67L).build()),
                    new Region("ÇAYCUMA", City.builder().id(67L).build()),
                    new Region("DEVREK", City.builder().id(67L).build()),
                    new Region("EREĞLİ", City.builder().id(67L).build()),
                    new Region("GÖKÇEBEY", City.builder().id(67L).build()),
                    new Region("KİLİMLİ", City.builder().id(67L).build()),
                    new Region("KOZLU", City.builder().id(67L).build()),
                    new Region("MERKEZ", City.builder().id(67L).build()),
                    new Region("AĞAÇÖREN", City.builder().id(68L).build()),
                    new Region("ESKİL", City.builder().id(68L).build()),
                    new Region("GÜLAĞAÇ", City.builder().id(68L).build()),
                    new Region("GÜZELYURT", City.builder().id(68L).build()),
                    new Region("MERKEZ", City.builder().id(68L).build()),
                    new Region("ORTAKÖY", City.builder().id(68L).build()),
                    new Region("SARIYAHŞİ", City.builder().id(68L).build()),
                    new Region("SULTANHANI", City.builder().id(68L).build()),
                    new Region("AYDINTEPE", City.builder().id(69L).build()),
                    new Region("DEMİRÖZÜ", City.builder().id(69L).build()),
                    new Region("MERKEZ", City.builder().id(69L).build()),
                    new Region("AYRANCI", City.builder().id(70L).build()),
                    new Region("BAŞYAYLA", City.builder().id(70L).build()),
                    new Region("ERMENEK", City.builder().id(70L).build()),
                    new Region("KAZIMKARABEKİR", City.builder().id(70L).build()),
                    new Region("MERKEZ", City.builder().id(70L).build()),
                    new Region("SARIVELİLER", City.builder().id(70L).build()),
                    new Region("BAHŞİLİ", City.builder().id(71L).build()),
                    new Region("BALIŞEYH", City.builder().id(71L).build()),
                    new Region("ÇELEBİ", City.builder().id(71L).build()),
                    new Region("DELİCE", City.builder().id(71L).build()),
                    new Region("KARAKEÇİLİ", City.builder().id(71L).build()),
                    new Region("KESKİN", City.builder().id(71L).build()),
                    new Region("MERKEZ", City.builder().id(71L).build()),
                    new Region("SULAKYURT", City.builder().id(71L).build()),
                    new Region("YAHŞİHAN", City.builder().id(71L).build()),
                    new Region("BEŞİRİ", City.builder().id(72L).build()),
                    new Region("GERCÜŞ", City.builder().id(72L).build()),
                    new Region("HASANKEYF", City.builder().id(72L).build()),
                    new Region("KOZLUK", City.builder().id(72L).build()),
                    new Region("MERKEZ", City.builder().id(72L).build()),
                    new Region("SASON", City.builder().id(72L).build()),
                    new Region("BEYTÜŞŞEBAP", City.builder().id(73L).build()),
                    new Region("CİZRE", City.builder().id(73L).build()),
                    new Region("GÜÇLÜKONAK", City.builder().id(73L).build()),
                    new Region("İDİL", City.builder().id(73L).build()),
                    new Region("MERKEZ", City.builder().id(73L).build()),
                    new Region("SİLOPİ", City.builder().id(73L).build()),
                    new Region("ULUDERE", City.builder().id(73L).build()),
                    new Region("AMASRA", City.builder().id(74L).build()),
                    new Region("KURUCAŞİLE", City.builder().id(74L).build()),
                    new Region("MERKEZ", City.builder().id(74L).build()),
                    new Region("ULUS", City.builder().id(74L).build()),
                    new Region("ÇILDIR", City.builder().id(75L).build()),
                    new Region("DAMAL", City.builder().id(75L).build()),
                    new Region("GÖLE", City.builder().id(75L).build()),
                    new Region("HANAK", City.builder().id(75L).build()),
                    new Region("MERKEZ", City.builder().id(75L).build()),
                    new Region("POSOF", City.builder().id(75L).build()),
                    new Region("ARALIK", City.builder().id(76L).build()),
                    new Region("KARAKOYUNLU", City.builder().id(76L).build()),
                    new Region("MERKEZ", City.builder().id(76L).build()),
                    new Region("TUZLUCA", City.builder().id(76L).build()),
                    new Region("ALTINOVA", City.builder().id(77L).build()),
                    new Region("ARMUTLU", City.builder().id(77L).build()),
                    new Region("ÇINARCIK", City.builder().id(77L).build()),
                    new Region("ÇİFTLİKKÖY", City.builder().id(77L).build()),
                    new Region("MERKEZ", City.builder().id(77L).build()),
                    new Region("TERMAL", City.builder().id(77L).build()),
                    new Region("EFLANİ", City.builder().id(78L).build()),
                    new Region("ESKİPAZAR", City.builder().id(78L).build()),
                    new Region("MERKEZ", City.builder().id(78L).build()),
                    new Region("OVACIK", City.builder().id(78L).build()),
                    new Region("SAFRANBOLU", City.builder().id(78L).build()),
                    new Region("YENİCE", City.builder().id(78L).build()),
                    new Region("ELBEYLİ", City.builder().id(79L).build()),
                    new Region("MERKEZ", City.builder().id(79L).build()),
                    new Region("MUSABEYLİ", City.builder().id(79L).build()),
                    new Region("POLATELİ", City.builder().id(79L).build()),
                    new Region("BAHÇE", City.builder().id(80L).build()),
                    new Region("DÜZİÇİ", City.builder().id(80L).build()),
                    new Region("HASANBEYLİ", City.builder().id(80L).build()),
                    new Region("KADİRLİ", City.builder().id(80L).build()),
                    new Region("MERKEZ", City.builder().id(80L).build()),
                    new Region("SUMBAS", City.builder().id(80L).build()),
                    new Region("TOPRAKKALE", City.builder().id(80L).build()),
                    new Region("AKÇAKOCA", City.builder().id(81L).build()),
                    new Region("CUMAYERİ", City.builder().id(81L).build()),
                    new Region("ÇİLİMLİ", City.builder().id(81L).build()),
                    new Region("GÖLYAKA", City.builder().id(81L).build()),
                    new Region("GÜMÜŞOVA", City.builder().id(81L).build()),
                    new Region("KAYNAŞLI", City.builder().id(81L).build()),
                    new Region("MERKEZ", City.builder().id(81L).build()),
                    new Region("YIĞILCA", City.builder().id(81L).build()));


            regionRepository.saveAll(regions);

            log.info("Saved Regions by Bootstrap");
        }

        if (userRepository.count() < 1) {

            City city = new City();
            city.setName("Example City");
            city = cityRepository.save(city);

            Region region = new Region();
            region.setName("Example Region");
            region.setCity(city);
            regionRepository.save(region);


            Address address = new Address();
            address.setName("admin");
            address.setRegion(region);
            addressRepository.save(address);


            User user = User.builder()
                    .name("Admin")
                    .surname("Admin")
                    .username("admin")
                    .email("admin@example.com")
                    .password(passwordEncoder.encode("StrongPass123"))
                    .phone("05554443322")
                    .age(52)
                    .address(address)
                    .role(Role.ADMIN)
                    .emailVerified(true)
                    .build();

            userRepository.save(user);

            log.info("User created by Bootstrap");
        }

    }
}

